make systemd timers configurable
puppetlabs/puppetlabs-pe_databases pull request #109
Opened 2022-09-05 11:57 UTC by SimonHoenscheid

2022-09-05 14:23 UTC, bastelfreak commented on manifests/init.pp
> +  String  $scripts_dir                           = "${install_dir}/scripts",
I suggest we can assume it's an absolute path:
```suggestion
  Stdlib::Absolutepath  $scripts_dir             = "${install_dir}/scripts",
```

2022-09-05 21:23 UTC, SimonHoenscheid commented on manifests/init.pp
> +  String  $install_dir                           = '/opt/puppetlabs/pe_databases',
```suggestion
  Stdlib::Absolutepath $install_dir                           = '/opt/puppetlabs/pe_databases',
```

2022-09-07 10:19 UTC, MartyEwings requested changes
Due to the nature of this module being shipped with PE, even using a supported module such as stdlib is not something we can do within the confines of this project.

you may just have to declare this as a string

2022-09-07 10:19 UTC, MartyEwings commented on manifests/init.pp
> +  Stdlib::Absolutepath $install_dir              = '/opt/puppetlabs/pe_databases',
This is a similar issue, as stdlib is not shipped with PE we cant add it to this module unfortunately

2022-09-07 11:22 UTC, bastelfreak commented
@MartyEwings why can't you vendor stdlib or other modules? Puppet Inc and Vox Pupuli are working on best practice guidelines since years. a few of the topics are:
* make datatypes as strict as possible
* reuse existing datatypes
* rely on puppet/systemd to unify unit management and reduce exec resources to reload systemd

I'm always a bit afraid that new users first check modules from Puppet and assume the used code style is the current best practice. pe_databases would be a bad example here. Would'nt it make more sense to rely on external modules and use them in PE?

2022-09-07 11:41 UTC, MartyEwings commented
@bastelfreak I work within the confines of a contributor to PE from the customer success organization, The overarching product team decides the standards of what is shipped with the Product. Im not sure what the specifics of the stdlib outside of PE discussion was, but there are a few good reasons I'm told.

With regards to dependencies, Everything my group puts in must not interfere with an offline installation, and the more dependencies I have the more my team must maintain and test and package.

In order to get the Product functions we require in, we have built everything for native Puppet Enterprise. Its not ideal, but its the practical way to contribute these functions we consider to be critical

2022-09-15 16:16 UTC, m0dular approved these changes
:+1

2022-09-15 16:49 UTC, MartyEwings approved these changes

2022-09-15 16:52 UTC, merged