(SUP-2374) Remove external module deps
puppetlabs/puppetlabs-pe_databases pull request #51
Opened 2021-04-27 11:35 UTC by MartyEwings

Prior to this commit, the module had dependencies for postgresql and stdlib.

stdlib appears to have been in metadata only, postgres functions are migrated to corresponding pe_postgres functions.

Passes local acceptance tests with pe_postgres module present, unsure as to how to perform spec testing utilising fixtures on internal repos in remote pipeline

2021-04-27 16:19 UTC, Sharpie requested changes
Looks like there's a default in `postgresql_settings.pp` that needs to be updated.

2021-04-27 16:19 UTC, Sharpie commented on manifests/postgresql_settings.pp
>    }
This resource default needs to be updated to `Pe_postgresql_conf`.

2021-04-28 14:33 UTC, jarretlavallee approved these changes
👍

2021-04-28 14:38 UTC, MartyEwings commented
OK iv tested this in 2021.1 its working fine as is, as we discovered none of the pe-postgres settings code is actually used post 2018.1

2021-04-30 08:52 UTC, MartyEwings commented
@Sharpie are you able to resolve the changes on this one so we can merge it, its been tested

2021-05-03 21:17 UTC, Sharpie approved these changes
Looks good 👍

2021-05-04 08:11 UTC, merged