(SUP-2677) Deprecate backup functionality
puppetlabs/puppetlabs-pe_databases pull request #91
Opened 2021-09-23 15:50 UTC by elainemccloskey

Added a warning if the parameter `manage_database_backups` is defined to output a deprecated message.

This only outputs to puppetserver.log and not during agent runs:

`2021-09-23T11:33:26.289Z WARN  [qtp351210790-526] [puppetserver] Scope(Class[Pe_databases]) The backup functionality in the pe_databases module has been deprecated and will be removed in a future release.`

A notify resource works to output in a Puppet run but results in a change on every Puppet run.

Also added 'warning' note to the readme about the deprecation.

2021-09-23 15:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-pe_databases?pullRequest=91) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-pe_databases?pullRequest=91) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-pe_databases?pullRequest=91) it.</sub>

2021-09-24 08:55 UTC, MartyEwings requested changes
The thinking on this is that we change it to a notify at the warning level so the client side will see it

2021-09-24 14:07 UTC, jarretlavallee commented on manifests/init.pp
> +        message  => 'The backup functionality in the pe_databases module has been deprecated and will be removed in a future release.',
This and the line below need to be indented

2021-10-01 11:05 UTC, elainemccloskey commented
closing to reopen using new logic that has been merged rather than rebasing

2021-10-01 11:05 UTC, closed without merging